### ISSUE TITLE
 npm run dev 报错

### ISSUE THREAD

**Issue by cubeer** [WsmDyj/mpvue#16]
$ npm run dev

> mpver-demo@0.1.0 dev D:\wechat\download\mpvue
> node build/dev-server.js

D:\wechat\download\mpvue\node_modules\mpvue-template-compiler\build.js:5785
    switch(fileExt.platform) {
                   ^

TypeError: Cannot read property 'platform' of undefined
    at Object.compileToWxml (D:\wechat\download\mpvue\node_modules\mpvue-template-compiler\build.js:5785:20)
    at genComponentWxml (D:\wechat\download\mpvue\node_modules\mpvue-loader\lib\mp-compiler\index.js:45:75)
    at Timeout.createWxml [as _onTimeout] (D:\wechat\download\mpvue\node_modules\mpvue-loader\lib\mp-compiler\index.js:92:19)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mpver-demo@0.1.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mpver-demo@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ghostsatan** [comment]
ERROR  Failed to compile with 7 errors                                                                         14:40:02

 error  in ./src/main.js

Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (E:\ken\github\mpvue\node_modules\_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)

 error  in ./src/pages/home/main.js

Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (E:\ken\github\mpvue\node_modules\_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)

 error  in ./src/pages/index/main.js

Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (E:\ken\github\mpvue\node_modules\_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)

 error  in ./src/pages/logs/main.js

Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (E:\ken\github\mpvue\node_modules\_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)

 error  in ./src/pages/my/main.js

Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (E:\ken\github\mpvue\node_modules\_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)

 error  in ./src/pages/order/main.js

Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (E:\ken\github\mpvue\node_modules\_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)

 error  in ./src/pages/pay/main.js

Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
    at Object.module.exports (E:\ken\github\mpvue\node_modules\_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)


一样报错

**Comment by wangxuguo** [comment]
> ERROR Failed to compile with 7 errors 14:40:02
> 
> error in ./src/main.js
> 
> Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> 
> error in ./src/pages/home/main.js
> 
> Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> 
> error in ./src/pages/index/main.js
> 
> Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> 
> error in ./src/pages/logs/main.js
> 
> Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> 
> error in ./src/pages/my/main.js
> 
> Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> 
> error in ./src/pages/order/main.js
> 
> Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> 
> error in ./src/pages/pay/main.js
> 
> Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> 
> 一样报错

解决这个问题了吗？

**Comment by ghostsatan** [comment]
> > ERROR Failed to compile with 7 errors 14:40:02
> > error in ./src/main.js
> > Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> > at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> > error in ./src/pages/home/main.js
> > Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> > at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> > error in ./src/pages/index/main.js
> > Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> > at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> > error in ./src/pages/logs/main.js
> > Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> > at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> > error in ./src/pages/my/main.js
> > Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> > at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> > error in ./src/pages/order/main.js
> > Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> > at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> > error in ./src/pages/pay/main.js
> > Module build failed: Error: [mpvue-loader] need "fileExt" option in file "build/vue-loader.conf.js"，init a new project and copy the directory "build/" to this porject, or just check the "fileExt" option
> > at Object.module.exports (E:\ken\github\mpvue\node_modules_mpvue-loader@1.4.0@mpvue-loader\lib\loader.js:55:11)
> > 一样报错
> 
> 解决这个问题了吗？

没有  困扰两天了 如果解决了 我会来这边说一下
